// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea_5_CrearUnRegistroConDetalleEnWpf.DAL;

namespace Tarea_5_CrearUnRegistroConDetalleEnWpf.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211028204857_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Tarea_5_CrearUnRegistroConDetalleEnWpf.Entidades.Permisos", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("PermisoId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            PermisoId = 1,
                            Descripcion = "Permiso para ser administrador del sistema.",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            PermisoId = 2,
                            Descripcion = "Permiso para entrar como moderador al sistema.",
                            Nombre = "Moderador"
                        },
                        new
                        {
                            PermisoId = 3,
                            Descripcion = "Permiso para entrar como usuario al sistema.",
                            Nombre = "Usuario"
                        },
                        new
                        {
                            PermisoId = 4,
                            Descripcion = "Permiso para entrar como invitado del sistema.",
                            Nombre = "Invitado"
                        });
                });

            modelBuilder.Entity("Tarea_5_CrearUnRegistroConDetalleEnWpf.Entidades.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Tarea_5_CrearUnRegistroConDetalleEnWpf.Entidades.RolesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsAsignado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("RolesDetalle");
                });

            modelBuilder.Entity("Tarea_5_CrearUnRegistroConDetalleEnWpf.Entidades.RolesDetalle", b =>
                {
                    b.HasOne("Tarea_5_CrearUnRegistroConDetalleEnWpf.Entidades.Roles", null)
                        .WithMany("Detalle")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tarea_5_CrearUnRegistroConDetalleEnWpf.Entidades.Roles", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
